# Use Actions: (Replaces run: --> uses:)
name: LTD Workflow
on: push
jobs:
  lint-test-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v5
      - name: Print Hosts
        uses: ./.github/actions/output-action
        with:
          file: 'inventory.yaml'